# Generated by Django 5.1.7 on 2025-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='min_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
