# Generated by Django 5.1.7 on 2025-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0003_prerequisite_min_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(default='NotGraded', max_length=10),
        ),
    ]
