# Generated by Django 5.1.7 on 2025-04-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0004_alter_enrollment_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='open_to_enrollment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_registration.role'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_registration.role'),
        ),
    ]
