# Generated by Django 5.1.7 on 2025-04-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0005_program_course_open_to_enrollment_course_quota_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Programs',
        ),
    ]
