# Generated by Django 5.1.7 on 2025-04-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0006_rename_program_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date_dropped',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_registration.programs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_registration.programs'),
        ),
    ]
