# Generated by Django 5.1.7 on 2025-04-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0008_advisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advisor',
            new_name='Advisors',
        ),
    ]
