# Generated by Django 5.1.7 on 2025-04-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0009_rename_advisor_advisors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
