# Generated by Django 5.1.7 on 2025-04-16 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0011_alter_advisors_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_registration.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_registration.user'),
        ),
    ]
